image: "jjanzic/docker-python3-opencv"

stages:
  - build
  - run
  - evaluate

build_project:
  stage: build
  script:
    - python -m venv venv
    - source venv/bin/activate
    - apt-get update && apt-get install libgl1 -y   # For opencv
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Installed everything!"
  artifacts:
    paths:
      - venv/

run_main:
  stage: run
  script:
    - source venv/bin/activate
    - apt-get update && apt-get install libgl1 -y
    - echo "Running main!"
    - python3 main.py --file_path ./dataset/pipeline/shorterVideo.avi --output_path ./Output.csv
  dependencies:
    - build_project
  artifacts:
    paths:
      - Output.csv

test_percentage:
  stage: evaluate
  script:
    - source venv/bin/activate
    - python3 evaluation.py --file_path ./Output.csv --ground_truth_path ./dataset/groundTruth.csv | grep -e "Score of Category I & II"
  dependencies:
    - run_main